resources:
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /local/lovelace/battery-entity.js?v=0.1
    type: module
  - url: /community_plugin/bom-weather-card/bom-weather-card.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module

decluttering_templates:
  climate-graph:
    card:
      type: custom:mini-graph-card
      hour24: true
      decimals: "[[decimals]]"
      animate: true
      align_header: left
      align_icon: left
      points_per_hour: 1
      show:
        labels: true
        fill: fade
      entities: "[[entities]]"
      line_color: "[[line_color]]"
  room:
    card:
      type: custom:vertical-stack-in-card
      title: "[[name]]"
      cards:
        - type: glance
          show_name: false
          entities: "[[glance]]"
        - type: entities
          style: |
            .card-content {
              padding-top: 0px;
            }
          show_header_toggle: false
          entities: "[[entities]]"

background: "#e5e5e5"

anchors:
  card-style-no-border-radius: &card-style-no-border-radius
    style: |
      ha-card {
        border-radius: 0px
      }

title: "Dom"
views:
  - id: home
    icon: mdi:home
    title: "Pomieszczenia"
    path: home
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: light.lamp_salon
            show_state: false
            show_label: true
            hold_action:
              action: more-info
            label: >
              [[[
                if (entity.state == 'on')
                  return 'włączona';
                else if (entity.state == 'off')
                  return 'wyłączona';
                else
                  return 'niedostępna';
              ]]]
            styles:
              card:
                - width: 100px
                - height: 100px
              label:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - color: var(--label-color-off)
              grid:
                - grid-template-areas: '"i" "n" "l"'
                - grid-template-columns: 1fr
                - grid-template-rows: 1fr min-content min-content
              img_cell:
                - align-self: start
                - text-align: start
              name:
                - justify-self: start
                - padding-left: 10px
                - font-weight: bold
                - font-size: 13px
              state:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - font-weight: bold
                - padding-left: 10px
            state:
              - value: 'unavailable'
                styles:
                  card:
                    - filter: opacity(20%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: light.bulbs_salon
            show_state: false
            show_label: true
            hold_action:
              action: more-info
            label: >
              [[[
                if (entity.state == 'on')
                  return 'włączone';
                else if (entity.state == 'off')
                  return 'wyłączone';
                else
                  return 'niedostępne';
              ]]]
            styles:
              card:
                - width: 100px
                - height: 100px
              label:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - color: var(--label-color-off)
              grid:
                - grid-template-areas: '"i" "n" "l"'
                - grid-template-columns: 1fr
                - grid-template-rows: 1fr min-content min-content
              img_cell:
                - align-self: start
                - text-align: start
              name:
                - justify-self: start
                - padding-left: 10px
                - font-weight: bold
                - font-size: 13px
              state:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - font-weight: bold
                - padding-left: 10px
            state:
              - value: 'unavailable'
                styles:
                  card:
                    - filter: opacity(20%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: light.leds_salon
            show_state: false
            show_label: true
            hold_action:
              action: more-info
            label: >
              [[[
                if (entity.state == 'on')
                  return 'włączone';
                else if (entity.state == 'off')
                  return 'wyłączone';
                else
                  return 'niedostępne';
              ]]]
            styles:
              card:
                - width: 100px
                - height: 100px
              label:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - color: var(--label-color-off)
              grid:
                - grid-template-areas: '"i" "n" "l"'
                - grid-template-columns: 1fr
                - grid-template-rows: 1fr min-content min-content
              img_cell:
                - align-self: start
                - text-align: start
              name:
                - justify-self: start
                - padding-left: 10px
                - font-weight: bold
                - font-size: 13px
              state:
                - font-size: 11px
                - font-family: Helvetica
                - padding: 0px 10px
                - justify-self: start
                - font-weight: bold
                - padding-left: 10px
            state:
              - value: 'unavailable'
                styles:
                  card:
                    - filter: opacity(20%)
                  icon:
                    - filter: grayscale(100%)
          - type: 'custom:mini-graph-card'
            entities:
              - sensor.temperature_salon
            hours_to_show: 24
            hour24: true
            animate: true
            decimals: 1
            font_size: 10
            font_size_header: 9
            height: 80
            show:
              icon: false


